### ISSUE TITLE
The include box on the following questions should include 'Include equivalent qualifications achieved anywhere outside England and Wales'

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/eq-prototypes#116]
The include box on the following questions should include 'Include equivalent qualifications achieved anywhere outside England and Wales'

https://deploy-preview-111--eq-prototypes.netlify.com/your-household-v12/individual-details-qualifications-degree
https://deploy-preview-111--eq-prototypes.netlify.com/your-household-v12/individual-details-qualifications-nvq-equivalent
https://deploy-preview-111--eq-prototypes.netlify.com/your-household-v12/individual-details-qualifications-a-level/
https://deploy-preview-111--eq-prototypes.netlify.com/your-household-v12/individual-details-qualifications-gcse

_Originally posted by @will-madebymoon in https://github.com/ONSdigital/eq-prototypes/pull/111#issuecomment-472926835_

**Comment by saedwards** [comment]
Fixed in latest

**Comment by will-madebymoon** [comment]
I'm still seeing the old content
