### ISSUE TITLE
An include box is not required on this page https://deploy-preview-111--eq-prototypes.netlify.com/your-household-v12/individual-details-qualifications-other-where

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/eq-prototypes#117]
An include box is not required on this page https://deploy-preview-111--eq-prototypes.netlify.com/your-household-v12/individual-details-qualifications-other-where

_Originally posted by @will-madebymoon in https://github.com/ONSdigital/eq-prototypes/pull/111#issuecomment-472927141_

**Comment by saedwards** [comment]
Fixed in latest
