### ISSUE TITLE
When selecting continue on an individual summary and returning to the hub only one section is displayed

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/eq-prototypes#129]
When selecting continue on an individual summary and returning to the hub only one section is displayed

See URL
https://deploy-preview-111--eq-prototypes.netlify.com/your-household-v12/hub/?survey=%23

**Comment by will-madebymoon** [comment]
<img width="1422" alt="Screenshot 2019-03-26 at 16 10 29" src="https://user-images.githubusercontent.com/8184622/55013777-bb4afb00-4fe1-11e9-865a-8b970767db2e.png">

**Comment by saedwards** [comment]
I think you'll need to reproduce this. This is a result of Javascript error and suspected null pointer exception. Once you've replicated this, can you save the session at: https://deploy-preview-111--eq-prototypes.netlify.com/your-household-v12/test-data and send me the file over Slack.

**Comment by will-madebymoon** [comment]
This is working as expected now.
